chore: test Drone integration

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -8,7 +8,7 @@ if [[ $current_branch =~ $main_branch ]]; then
     exit 1
 fi
 
-valid_branch_names="^(feature|bugfix|improvement|library|prerelease|release|hotfix)\/[a-z0-9._-]+$"
+valid_branch_names="^(feature|bugfix|improvement|library|prerelease|hotfix)\/[a-z0-9._-]+$"
 if [[ ! $current_branch =~ $valid_branch_names ]]; then
     echo -e "\033[1;31m[ERROR] Your branch name is illegal. Please rename your branch with using following regex: $valid_branch_names\033[0m"
     exit 1
@@ -20,4 +20,10 @@ if [[ ! $1 =~ $valid_commit ]]; then
     exit 1
 fi
 
-exit 1
+./mvnw clean validate
+if [ "$?" -ne 0 ]; then
+    echo -e "\033[1;31m[ERROR] Maven Validate unsuccessful.\033[0m"
+    exit 1
+fi
+
+exit 0
